version: "2"

services:
    orderer0.health.com:
        container_name: orderer0.health.com
        extends:
            file: peer-base.yaml
            service: orderer-base
        volumes:
            - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer0.genesis.block
            - ../crypto-config/ordererOrganizations/health.com/orderers/orderer0.health.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/health.com/orderers/orderer0.health.com/tls/:/var/hyperledger/orderer/tls
            - orderer0.health.com:/var/hyperledger/production/orderer
        ports:
            - 7050:7050

    peer0.patient.health.com:
        container_name: peer0.patient.health.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.patient.health.com
            - CORE_PEER_ADDRESS=peer0.patient.health.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.patient.health.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.phc.health.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.health.com:7051
            - CORE_PEER_LOCALMSPID=PatientMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.patient.health.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/patient.health.com/peers/peer0.patient.health.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/patient.health.com/peers/peer0.patient.health.com/tls:/etc/hyperledger/fabric/tls
            - peer0.patient.health.com:/var/hyperledger/production
        ports:
            - 7051:7051

    peer0.phc.health.com:
        container_name: peer0.phc.health.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.phc.health.com
            - CORE_PEER_ADDRESS=peer0.phc.health.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.phc.health.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.phc.health.com:8051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.health.com:7051
            - CORE_PEER_LOCALMSPID=PHCMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.phc.health.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/phc.health.com/peers/peer0.phc.health.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/phc.health.com/peers/peer0.phc.health.com/tls:/etc/hyperledger/fabric/tls
            - peer0.phc.health.com:/var/hyperledger/production
        ports:
            - 8051:8051

    peer0.hospital.health.com:
        container_name: peer0.hospital.health.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.hospital.health.com
            - CORE_PEER_ADDRESS=peer0.hospital.health.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.health.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.health.com:9051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.health.com:7051
            - CORE_PEER_LOCALMSPID=HospitalMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.hospital.health.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/hospital.health.com/peers/peer0.hospital.health.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/hospital.health.com/peers/peer0.hospital.health.com/tls:/etc/hyperledger/fabric/tls
            - peer0.hospital.health.com:/var/hyperledger/production
        ports:
            - 9051:9051

    peer0.healthadmin.health.com:
        container_name: peer0.healthadmin.health.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.healthadmin.health.com
            - CORE_PEER_ADDRESS=peer0.healthadmin.health.com:10051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_CHAINCODEADDRESS=peer0.healthadmin.health.com:10052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.healthadmin.health.com:10051
            #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.health.com:7051
            - CORE_PEER_LOCALMSPID=HealthAdminMSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.healthadmin.health.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/healthadmin.health.com/peers/peer0.healthadmin.health.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/healthadmin.health.com/peers/peer0.healthadmin.health.com/tls:/etc/hyperledger/fabric/tls
            - peer0.healthadmin.health.com:/var/hyperledger/production
        ports:
            - 10051:10051

    ca.patient.health.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-patient
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.patient.health.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=7054
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.patient.health.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/patient.health.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.phc.health.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-phc
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.phc.health.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=8054
        ports:
            - "8054:8054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.phc.health.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/phc.health.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.hospital.health.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-hospital
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.health.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=9054
        ports:
            - "9054:9054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hospital.health.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/hospital.health.com/ca/:/etc/hyperledger/fabric-ca-server-config

    ca.healthadmin.health.com:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-healthadmin
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.healthadmin.health.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=10054
        ports:
            - "10054:10054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.healthadmin.health.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/healthadmin.health.com/ca/:/etc/hyperledger/fabric-ca-server-config
