---
Organizations:
    - &OrdererOrg
      Name: OrdererOrg
      ID: OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/health.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"

    - &Patient
      Name: PatientMSP
      ID: PatientMSP
      MSPDir: crypto-config/peerOrganizations/patient.health.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PatientMSP.admin', 'PatientMSP.peer', 'PatientMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('PatientMSP.admin', 'PatientMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('PatientMSP.admin')"

    - &PHC
      Name: PHCMSP
      ID: PHCMSP
      MSPDir: crypto-config/peerOrganizations/phc.health.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PHCMSP.admin', 'PHCMSP.peer', 'PHCMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('PHCMSP.admin', 'PHCMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('PHCMSP.admin')"

    - &Hospital
      Name: HospitalMSP
      ID: HospitalMSP
      MSPDir: crypto-config/peerOrganizations/hospital.health.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('HospitalMSP.admin', 'HospitalMSP.peer', 'HospitalMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('HospitalMSP.admin', 'HospitalMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('HospitalMSP.admin')"

    - &HealthAdmin
      Name: HealthAdminMSP
      ID: HealthAdminMSP
      MSPDir: crypto-config/peerOrganizations/healthadmin.health.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('HealthAdminMSP.admin', 'HealthAdminMSP.peer', 'HealthAdminMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('HealthAdminMSP.admin', 'HealthAdminMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('HealthAdminMSP.admin')"

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.health.com:7050

    BatchTimeout: 250ms
    BatchSize:
        MaxMessageCount: 50
        AbsoluteMaxBytes: 100 MB
        PreferredMaxBytes: 1 MB

    MaxChannels: 0
    EtcdRaft:
        Consenters:
            - Host: orderer0.health.com
              Port: 7050
              ClientTLSCert: crypto-config/ordererOrganizations/health.com/orderers/orderer0.health.com/tls/server.crt
              ServerTLSCert: crypto-config/ordererOrganizations/health.com/orderers/orderer0.health.com/tls/server.crt

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    HEALTHOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Patient
                    - *PHC
                    - *Hospital
                    - *HealthAdmin

    HEALTHChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Patient
                - *PHC
                - *Hospital
                - *HealthAdmin

            Capabilities:
                <<: *ApplicationCapabilities
