OrdererOrgs:
    - Name: Orderer
      Domain: health.com
      EnableNodeOUs: true
      Template:
          Count: 3

PeerOrgs:
    - Name: Patient
      Domain: patient.health.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: PHC
      Domain: phc.health.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: Hospital
      Domain: hospital.health.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1

    - Name: HealthAdmin
      Domain: healthadmin.health.com
      EnableNodeOUs: true
      Template:
          Count: 1
      Users:
          Count: 1
