version: "2"

volumes:
    orderer0.health.com:
    orderer1.health.com:
    orderer2.health.com:
    peer0.patient.health.com:
    peer0.phc.health.com:
    peer0.hospital.health.com:
    peer0.healthadmin.health.com:
    peer1.patient.health.com:
    peer1.phc.health.com:
    peer1.hospital.health.com:
    peer1.healthadmin.health.com:
    ca.patient.health.com:
    ca.phc.health.com:
    ca.hospital.health.com:
    ca.healthadmin.health.com:

networks:
    healthnet:

services:
    orderer0.health.com:
        extends:
            file: base/docker-compose-base.yaml
            service: orderer0.health.com
        container_name: orderer0.health.com
        networks:
            - healthnet
        depends_on:
            - ca.patient.health.com
            - ca.phc.health.com
            - ca.hospital.health.com
            - ca.healthadmin.health.com

    orderer1.health.com:
        extends:
            file: base/docker-compose-base.yaml
            service: orderer1.health.com
        container_name: orderer1.health.com
        networks:
            - healthnet
        depends_on:
            - ca.patient.health.com
            - ca.phc.health.com
            - ca.hospital.health.com
            - ca.healthadmin.health.com

    orderer2.health.com:
        extends:
            file: base/docker-compose-base.yaml
            service: orderer2.health.com
        container_name: orderer2.health.com
        networks:
            - healthnet
        depends_on:
            - ca.patient.health.com
            - ca.phc.health.com
            - ca.hospital.health.com
            - ca.healthadmin.health.com

    peer0.patient.health.com:
        container_name: peer0.patient.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.patient.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer0.patient.health.com

    peer0.phc.health.com:
        container_name: peer0.phc.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.phc.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer0.phc.health.com

    peer0.hospital.health.com:
        container_name: peer0.hospital.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.hospital.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer0.hospital.health.com

    peer0.healthadmin.health.com:
        container_name: peer0.healthadmin.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.healthadmin.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer0.healthadmin.health.com

    peer1.patient.health.com:
        container_name: peer1.patient.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.patient.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer1.patient.health.com

    peer1.phc.health.com:
        container_name: peer1.phc.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.phc.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer1.phc.health.com

    peer1.hospital.health.com:
        container_name: peer1.hospital.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.hospital.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer1.hospital.health.com

    peer1.healthadmin.health.com:
        container_name: peer1.healthadmin.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.healthadmin.health.com
        networks:
            - healthnet
        depends_on:
            - orderer0.health.com
            - couchdb.peer1.healthadmin.health.com

    ca.patient.health.com:
        container_name: ca.patient.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: ca.patient.health.com
        networks:
            - healthnet

    ca.phc.health.com:
        container_name: ca.phc.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: ca.phc.health.com
        networks:
            - healthnet

    ca.hospital.health.com:
        container_name: ca.hospital.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: ca.hospital.health.com
        networks:
            - healthnet

    ca.healthadmin.health.com:
        container_name: ca.healthadmin.health.com
        extends:
            file: base/docker-compose-base.yaml
            service: ca.healthadmin.health.com
        networks:
            - healthnet

    couchdb.peer0.patient.health.com:
        container_name: couchdb.peer0.patient.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "5984:5984"
        networks:
            - healthnet

    couchdb.peer0.phc.health.com:
        container_name: couchdb.peer0.phc.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "6984:5984"
        networks:
            - healthnet

    couchdb.peer0.hospital.health.com:
        container_name: couchdb.peer0.hospital.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "7984:5984"
        networks:
            - healthnet

    couchdb.peer0.healthadmin.health.com:
        container_name: couchdb.peer0.healthadmin.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "8984:5984"
        networks:
            - healthnet

    couchdb.peer1.patient.health.com:
        container_name: couchdb.peer1.patient.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "5985:5984"
        networks:
            - healthnet

    couchdb.peer1.phc.health.com:
        container_name: couchdb.peer1.phc.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "6985:5984"
        networks:
            - healthnet

    couchdb.peer1.hospital.health.com:
        container_name: couchdb.peer1.hospital.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "7985:5984"
        networks:
            - healthnet

    couchdb.peer1.healthadmin.health.com:
        container_name: couchdb.peer1.healthadmin.health.com
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        ports:
            - "8985:5984"
        networks:
            - healthnet

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=peer0.patient.health.com:7051
            - CORE_PEER_LOCALMSPID=PatientMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.health.com/peers/peer0.patient.health.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.health.com/peers/peer0.patient.health.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.health.com/peers/peer0.patient.health.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patient.health.com/users/Admin@patient.health.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./../chaincode/:/opt/gopath/src/
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        depends_on:
            - orderer0.health.com
            - orderer1.health.com
            - orderer2.health.com
            - peer0.patient.health.com
            - peer0.phc.health.com
            - peer0.hospital.health.com
            - peer0.healthadmin.health.com
            - peer1.patient.health.com
            - peer1.phc.health.com
            - peer1.hospital.health.com
            - peer1.healthadmin.health.com
            - ca.patient.health.com
            - ca.phc.health.com
            - ca.hospital.health.com
            - ca.healthadmin.health.com
        networks:
            - healthnet
