testConfig: &testConfig
    rtps: &test_rtps 25
    ctps: &test_ctps 250
    # etps: &test_etps 500
    txDuration: &test_txduration 20
    seed: &test_seed 251638868342

test:
    name: caliper_benchmark
    description: test_benchmark
    workers:
        type: local
        number: 10
    rounds:
        - label: readAsset
          description: Read Asset benchmark
          chaincodeId: patientprofile_cc
          txDuration: *test_txduration
          rateControl:
              type: fixed-rate
              opts:
                  tps: *test_rtps
          callback: benchmarks/callbacks/readAssetBenchmark.js
          arguments:
              assets: 10
              seed: *test_seed
        - label: createAsset
          description: Create Asset benchmark
          chaincodeId: patientprofile_cc
          txDuration: *test_txduration
          rateControl:
              type: fixed-rate
              opts:
                  tps: *test_ctps
          callback: benchmarks/callbacks/createAssetBenchmark.js
          arguments:
              assets: 10
        # - label: emergencyDetection
        #   description: Emergency Detection benchmark
        #   chaincodeId: emergencydetection_cc
        #   txDuration: *test_txduration
        #   rateControl:
        #       type: fixed-rate
        #       opts:
        #           tps: *test_etps
        #   callback: benchmarks/callbacks/emergencyDetectionBenchmark.js
        #   arguments:
        #       assets: 10
        #       seed: *test_seed

monitor:
    type:
        - docker
        - process
    docker:
        containers:
            - all
        charting:
            polar:
                metrics:
                    - all
            bar:
                metrics:
                    - Memory(max)
    process:
        processes:
            - command: node
              arguments: fabricClientWorker.js
              multiOutput: avg
        charting:
            bar:
                metrics:
                    - all

observer:
    type: local
    interval: 5
